#include "reduced_basic_deck_provider.h"

#include <vector>

#include "card.h"
#include "cards/_cards.h"

namespace model::decks
{
ReducedBasicDeckProvider::ReducedBasicDeckProvider() noexcept {}
ReducedBasicDeckProvider::~ReducedBasicDeckProvider() noexcept {}

std::vector<Card*> ReducedBasicDeckProvider::GenerateDeck( const GameModel& model ) {
    return {
        new cards::AdaptedLichen( model ),
        new cards::AdvancedEcosystems( model ),
        new cards::AerobrakedAmmoniaAsteroid( model ),
        new cards::Algae( model ),
        new cards::AquiferPumping( model ),
        new cards::Archaebacteria( model ),
        new cards::ArcticAlgae( model ),
        new cards::ArtificalLake( model ),
        new cards::Asteroid( model ),
        new cards::AsteroidMining( model ),
        new cards::BeamFromAThoriumAsteroid( model ),
        new cards::BigAsteroid( model ),
        new cards::BiomassCombustors( model ),
        new cards::BlackPolarDust( model ),
        new cards::BreathingFilters( model ),
        new cards::Bushes( model ),
        new cards::CarbonateProcessing( model ),
        new cards::CloudSeeding( model ),
        new cards::ColonizerTrainingCamp( model ),
        new cards::Comet( model ),
        new cards::ConvoyFromEuropa( model ),
        new cards::CupolaCity( model ),
        new cards::DeepWellHeating( model ),
        new cards::DeimosDown( model ),
        new cards::DesignedMicroorganisms( model ),
        new cards::DomedCrater( model ),
        new cards::DustSeals( model ),
        new cards::EnergySaving( model ),
        new cards::EosChasmaNationalPark( model ),
        new cards::EquatorialMagnetizer( model ),
        new cards::Farming( model ),
        new cards::FoodFactory( model ),
        new cards::FueledGenerators( model ),
        new cards::FusionPower( model ),
        new cards::GhgFactories( model ),
        new cards::GeothermalPower( model ),
        new cards::GiantIceAsteroid( model ),
        new cards::GiantSpaceMirror( model ),
        new cards::Grass( model ),
        new cards::GreatDam( model ),
        new cards::Greenhouses( model ),
        new cards::HeatTrappers( model ),
        new cards::Heather( model ),
        new cards::IceAsteroid( model ),
        new cards::IceCapMelting( model ),
        new cards::ImmigrantCity( model ),
        new cards::ImmigrationShuttles( model ),
        new cards::ImportOfAdvancedGhg( model ),
        new cards::ImportedGhg( model ),
        new cards::ImportedNitrogen( model ),
        new cards::IndustrialMicrobes( model ),
        new cards::Insects( model ),
        new cards::Insulation( model ),
        new cards::Ironworks( model ),
        new cards::KelpFarming( model ),
        new cards::LakeMarineris( model ),
        new cards::Lichen( model ),
        new cards::LunarBeam( model ),
        new cards::MagneticFieldDome( model ),
        new cards::MagneticFieldGenerators( model ),
        new cards::Mangrove( model ),
        new cards::MartianRails( model ),
        new cards::MethaneFromTitan( model ),
        new cards::MicroMills( model ),
        new cards::MiningExpedition( model ),
        new cards::Moss( model ),
        new cards::NitrogenRichAsteroid( model ),
        new cards::NitrophilicMoss( model ),
        new cards::NoctisCity( model ),
        new cards::NoctisFarming( model ),
        new cards::NuclearPower( model ),
        new cards::OpenCity( model ),
        new cards::OptimalAerobraking( model ),
        new cards::OreProcessor( model ),
        new cards::PermafrostExtraction( model ),
        new cards::PeroxidePower( model ),
        new cards::Plantation( model ),
        new cards::PowerGrid( model ),
        new cards::PowerPlant( model ),
        new cards::ProtectedValley( model ),
        new cards::RadChemFactory( model ),
        new cards::ReleaseOfInertGases( model ),
        new cards::ResearchOutpost( model ),
        new cards::RoverConstruction( model ),
        new cards::Shuttles( model ),
        new cards::SoilFactory( model ),
        new cards::SolarPower( model ),
        new cards::SolarWindPower( model ),
        new cards::Soletta( model ),
        new cards::SpaceMirrors( model ),
        new cards::Steelworks( model ),
        new cards::StripMine( model ),
        new cards::SubterraneanReservoir( model ),
        new cards::TectonicStressPower( model ),
        new cards::TowingAComet( model ),
        new cards::Trees( model ),
        new cards::TundraFarming( model ),
        new cards::UndergroundCity( model ),
        new cards::UndergroundDetonations( model ),
        new cards::UrbanizedArea( model ),
        new cards::WaterImportFromEuropa( model ),
        new cards::WaterSplittingPlant( model ),
        new cards::WavePower( model ),
        new cards::Windmills( model ),
        new cards::Worms( model ),
        new cards::Zeppelins( model )
    };
}
}
